name: Auto Assign and Label

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  assign-reviewers-assignees:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0
